import {chromium} from 'playwright-core';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='../../artifacts/dashboard_daily_fold_settings_2026_10_11/ui';await mkdir(out,{recursive:true});
const docs=JSON.parse(await readFile('../../artifacts/dashboard_operations_2026_10_10/production-docs.json','utf8'));
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try {for(const width of [360,752,1440]){const page=await browser.newPage({viewport:{width,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/__/firebase/**',r=>r.fulfill({body:'',contentType:'text/javascript'}));await page.route('**/assets/js/mock.js',r=>r.fulfill({body:'export function buildMockDocs(){return '+JSON.stringify(docs)+';}',contentType:'text/javascript'}));await page.goto('http://127.0.0.1:8794/?demo');await page.locator('#ch-users .hit').waitFor();assert.equal(await page.locator('main > section').first().getAttribute('class'),'card span-12 daily-overview');assert.equal(await page.locator('[data-action="daily-day"]').count(),10);assert.equal(await page.getByText('서비스가 성장하고, 제대로 쓰이고 있는가',{exact:true}).count(),0);
for(const n of [0,4,9]){const day=page.locator('[data-action="daily-day"]').nth(n);const date=await day.getAttribute('data-date');await day.click();const i=docs.series.dates.indexOf(date);const readout=await page.locator('#daily-readout').textContent();assert.ok(readout.includes('DAU '+docs.series.dau[i].toLocaleString('ko-KR')+'명'));assert.ok(readout.includes('MAU '+docs.series.mau[i].toLocaleString('ko-KR')+'명'));assert.equal(await day.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#ch-users .xh').evaluate(e=>e.style.display),'');}
const hit=page.locator('#ch-users .hit');await hit.scrollIntoViewIfNeeded();const box=await hit.boundingBox();await page.mouse.click(box.x+box.width*.22,box.y+box.height*.5);assert.ok((await page.locator('#daily-readout').textContent()).includes('DAU'));await page.locator('h1').click();assert.equal(await page.locator('#ch-users .xh').evaluate(e=>e.style.display),'none');
await page.getByRole('button',{name:'7일',exact:true}).click();assert.equal(await page.locator('[data-action="daily-day"]').count(),10);
const names=await page.locator('.ops-table [data-event]').evaluateAll(rows=>rows.map(r=>r.dataset.event));const selected=docs.summary.eventsByRange[7];const counts=names.filter(n=>selected.events.some(e=>e.name===n)).map(n=>selected.events.find(e=>e.name===n).count);assert.deepEqual(counts,[...counts].sort((a,b)=>b-a));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+'/overview-'+width+'.png',fullPage:true});await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await page.screenshot({path:out+'/dark-'+width+'.png',fullPage:true});assert.deepEqual(errors,[]);results.push({width,tenDays:true,clickThreeDates:true,pointerSelection:true,outsideClear:true,rangeIndependent:true,featuresDescending:true,errors});await page.close();}await writeFile(out+'/../browser-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();}
