import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Same order as the requested review: pt-BR, de-DE, English, Hindi; Korean meaning.
COPY = {
 'permissionFullScreen': ['Alarme na tela de bloqueio', 'Wecker auf dem Sperrbildschirm', 'Lock screen alarm display', 'लॉक स्क्रीन पर अलार्म दिखाना', '잠금화면 알람 표시'],
 'permissionFullScreenDesc': ['Mostra a tela do alarme quando o celular está bloqueado. Permita notificações em tela cheia.', 'Zeigt den Wecker bei gesperrtem Bildschirm an. Erlaube Vollbildbenachrichtigungen.', 'Displays the alarm screen while your phone is locked. Allow full-screen notifications.', 'फ़ोन लॉक होने पर अलार्म स्क्रीन दिखाता है। फ़ुल-स्क्रीन सूचनाओं की अनुमति दें।', '화면이 잠겨 있을 때 알람 화면을 표시합니다. 전체 화면 알림을 허용해 주세요.'],
 'permissionGranted': ['Permitido', 'Erlaubt', 'Allowed', 'अनुमति है', '허용'],
 'permissionNeedsSettings': ['Precisa de configuração', 'Einstellung erforderlich', 'Setup needed', 'सेटिंग बदलनी है', '설정 필요'],
 'permissionUnknown': ['Não foi possível verificar', 'Status nicht prüfbar', 'Could not check', 'स्थिति जाँची नहीं जा सकी', '확인 불가'],
 'permissionNotApplicable': ['Não requer configuração nesta versão do Android', 'Keine separate Einstellung in dieser Android-Version', 'No separate setting on this Android version', 'इस Android संस्करण में अलग सेटिंग की ज़रूरत नहीं है', '이 Android 버전에서는 별도 설정이 필요 없어요'],
 'permissionSettingsTitle': ['Permissões do alarme', 'Weckerberechtigungen', 'Alarm permissions', 'अलार्म की अनुमतियाँ', '알람 권한 설정'],
 'permissionReturnGuide': ['Depois de configurar, volte ao ShiftBell com o botão Voltar do sistema. Vamos verificar as permissões novamente. Os nomes podem variar conforme o aparelho, a versão do sistema e o idioma das configurações.', 'Kehre nach dem Einstellen mit der System-Zurücktaste zu ShiftBell zurück. Die Berechtigungen werden erneut geprüft. Namen können je nach Gerät, Systemversion und Einstellungssprache abweichen.', 'After changing settings, use the system Back button to return to ShiftBell. We will check permissions again. Names may vary by device, OS version and settings language.', 'सेटिंग बदलने के बाद सिस्टम के वापस बटन से ShiftBell में लौटें। हम अनुमतियाँ फिर जाँचेंगे। नाम डिवाइस, सिस्टम संस्करण और सेटिंग की भाषा के अनुसार अलग हो सकते हैं।', '설정을 마친 뒤 시스템 뒤로 가기로 ShiftBell에 돌아오면 권한 상태를 다시 확인합니다. 기기·OS 버전·설정 언어에 따라 이름이 다를 수 있어요.'],
 'permissionOpenFailed': ['Não foi possível abrir as configurações. Abra Configurações → Apps → ShiftBell → Permissões ou Notificações.', 'Die Einstellungen konnten nicht geöffnet werden. Öffne Einstellungen → Apps → ShiftBell → Berechtigungen oder Benachrichtigungen.', 'Could not open settings. Open Settings → Apps → ShiftBell → Permissions or Notifications.', 'सेटिंग नहीं खुल सकी। सेटिंग → ऐप्स → ShiftBell → अनुमतियाँ या सूचनाएँ खोलें।', '설정을 열지 못했어요. 휴대폰 설정 → 앱 → ShiftBell → 권한 또는 알림에서 확인해 주세요.'],
 'permissionOverlayRouteGuide': ['Se aparecer uma lista de apps, selecione ShiftBell e permita a exibição sobre outros apps.', 'Wenn eine App-Liste erscheint, wähle ShiftBell und erlaube die Anzeige über anderen Apps.', 'If an app list appears, select ShiftBell and allow display over other apps.', 'अगर ऐप्स की सूची खुले, तो ShiftBell चुनकर दूसरे ऐप्स के ऊपर दिखाने की अनुमति दें।', '앱 목록이 나오면 ShiftBell을 선택한 뒤 다른 앱 위에 표시를 허용해 주세요.'],
 'permissionAlarmChannelBlocked': ['As notificações de controle do alarme estão bloqueadas', 'Benachrichtigungen zur Weckersteuerung sind blockiert', 'Alarm control notifications are blocked', 'अलार्म नियंत्रित करने की सूचनाएँ बंद हैं', '알람 제어 알림 채널이 차단되어 있어요'],
 'permissionAlarmChannelUnknown': ['Não foi possível verificar o canal de controle do alarme', 'Der Kanal zur Weckersteuerung konnte nicht geprüft werden', 'Could not check the alarm control channel', 'अलार्म नियंत्रण सूचना चैनल जाँचा नहीं जा सका', '알람 제어 알림 채널을 확인하지 못했어요'],
 'permissionLockScreenHelp': ['O alarme não aparece na tela de bloqueio?', 'Kein Wecker auf dem Sperrbildschirm?', 'Alarm missing from the lock screen?', 'लॉक स्क्रीन पर अलार्म नहीं दिख रहा?', '잠금화면에 알람이 안 보이나요?'],
 'permissionLockScreenHelpBody': ['Confira as permissões do alarme e as restrições de bateria e de execução em segundo plano. Para testar, configure um alarme de turno para daqui a alguns minutos e bloqueie o celular. As permissões permitidas não garantem a exibição em todos os aparelhos.', 'Prüfe die Weckerberechtigungen sowie Akku- und Hintergrundbeschränkungen. Stelle zum Testen einen Schichtwecker für in wenigen Minuten und sperre das Telefon. Erlaubte Berechtigungen garantieren die Anzeige nicht auf jedem Gerät.', 'Check alarm permissions and battery and background restrictions. To test, set a shift alarm a few minutes ahead and lock your phone. Allowed permissions do not guarantee display on every device.', 'अलार्म की अनुमतियाँ, बैटरी और बैकग्राउंड की पाबंदियाँ जाँचें। परीक्षण के लिए कुछ मिनट बाद का शिफ्ट अलार्म सेट करें और फ़ोन लॉक करें। अनुमतियाँ होने पर भी हर डिवाइस पर स्क्रीन दिखने की गारंटी नहीं है।', '알람 권한과 배터리·백그라운드 제한을 확인해 주세요. 직접 확인하려면 몇 분 뒤의 근무 알람을 설정하고 휴대폰을 잠가 보세요. 권한이 허용되어도 모든 기기에서 화면 표시를 보장하지는 않아요.'],
 'permissionXiaomiTitle': ['Alarme na tela de bloqueio da Xiaomi', 'Xiaomi-Wecker auf dem Sperrbildschirm', 'Xiaomi lock screen alarm settings', 'Xiaomi लॉक स्क्रीन अलार्म सेटिंग', '샤오미 잠금화면 알람 설정'],
 'permissionXiaomiBody': ['Na Xiaomi, pode ser necessária uma configuração adicional. Em Outras permissões (Other permissions), selecione Abrir novas janelas em segundo plano (Open new windows while running in the background) e escolha Sempre permitir (Always allow). Esses nomes são orientações e podem variar.', 'Bei Xiaomi kann eine zusätzliche Einstellung nötig sein. Wähle unter Weitere Berechtigungen (Other permissions) Neue Fenster im Hintergrund öffnen (Open new windows while running in the background) und dann Immer erlauben (Always allow). Diese Bezeichnungen dienen als Orientierung und können abweichen.', 'Xiaomi may need an additional setting to display lock screen alarms. Under Other permissions, select Open new windows while running in the background, then Always allow. Names may vary by device and OS version.', 'Xiaomi पर लॉक स्क्रीन अलार्म दिखाने के लिए अतिरिक्त सेटिंग की ज़रूरत हो सकती है। अन्य अनुमतियाँ (Other permissions) में बैकग्राउंड में नई विंडो खोलना (Open new windows while running in the background) चुनें, फिर हमेशा अनुमति दें (Always allow) चुनें। ये नाम मार्गदर्शन के लिए हैं और अलग हो सकते हैं।', '샤오미에서는 잠금화면 알람을 표시하려면 추가 설정이 필요할 수 있어요. 기타 권한(Other permissions)에서 백그라운드에서 새 창 열기(Open new windows while running in the background)를 선택하고 항상 허용(Always allow)으로 변경해 주세요. 이 명칭은 안내 번역이며 기기에 따라 다를 수 있어요.'],
 'permissionOpenOemSettings': ['Abrir configurações de permissões', 'Berechtigungseinstellungen öffnen', 'Open permission settings', 'अनुमति सेटिंग खोलें', '권한 설정 열기'],
 'permissionOpenFullScreenSettings': ['Abrir configurações de tela cheia', 'Vollbildbenachrichtigungen öffnen', 'Open full-screen notification settings', 'फ़ुल-स्क्रीन सूचना सेटिंग खोलें', '전체 화면 알림 설정 열기'],
 'permissionStillDenied': ['Ainda não permitido', 'Noch nicht erlaubt', 'Still not allowed', 'अभी अनुमति नहीं है', '아직 허용되지 않았어요'],
}
for i, lang in enumerate(['pt', 'de', 'en', 'hi', 'ko']):
 p = ROOT/f'lib/l10n/app_{lang}.arb'
 data = json.loads(p.read_text('utf-8'))
 data.update({key: values[i] for key, values in COPY.items()})
 p.write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n', 'utf-8')
