"""Generate pre-Flutter browser/install metadata from reviewed release copy."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / 'web'
base = json.loads((WEB / 'manifest.json').read_text('utf-8'))
copy = {}
for lang in ['ko', 'pt', 'de', 'en', 'hi']:
    arb = json.loads((ROOT / f'lib/l10n/app_{lang}.arb').read_text('utf-8'))
    item = {'name': arb['appTitle'],
            'title': f"{arb['appTitle']} - {arb['friendShareTitle']}",
            'description': arb['publicWebShareBody']}
    if lang == 'ko':
        # Preserve the existing Korean web metadata, independent of app copy.
        item.update(json.loads((WEB / 'l10n/metadata_ko.json').read_text('utf-8')))
    copy[lang] = item
    manifest = dict(base, name=item.get('manifestName', item['title']), short_name=item['name'],
                    description=item.get('manifestDescription', item['description']), lang=lang)
    (WEB / f'manifest_{lang}.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n', 'utf-8')
script = '''// Generated by tools/generate_web_locale_assets.py. Do not edit.
(function () {
  'use strict';
  const copy = __COPY__;
  function updateLocale() {
    const primary = (navigator.languages && navigator.languages[0]) || navigator.language || 'en';
    const requested = primary.toLowerCase().split(/[-_]/)[0];
    const lang = Object.prototype.hasOwnProperty.call(copy, requested) ? requested : 'en';
    const text = copy[lang];
    document.documentElement.lang = lang;
    document.title = text.title;
    for (const [selector, value] of [
      ['meta[name="description"]', text.metaDescription || text.description],
      ['meta[property="og:title"]', text.title],
      ['meta[property="og:description"]', text.description],
      ['meta[name="apple-mobile-web-app-title"]', text.name]
    ]) {
      const element = document.querySelector(selector);
      if (element) element.setAttribute('content', value);
    }
    const manifest = document.querySelector('link[rel="manifest"]');
    if (manifest) manifest.setAttribute('href', 'manifest_' + lang + '.json');
  }
  updateLocale();
  window.addEventListener('languagechange', updateLocale);
})();
'''.replace('__COPY__', json.dumps(copy, ensure_ascii=False, indent=2))
(WEB / 'locale_bootstrap.js').write_text(script, 'utf-8')
print('Generated 5 localized manifests and browser metadata bootstrap.')
