"""Generate explicitly scoped Korean copy; not part of Flutter's ARB fallback."""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def generate():
 data=json.loads((ROOT/'lib/l10n/korean_only/messages_ko.json').read_text('utf-8'))
 lines=["// Generated by tools/generate_korean_only_copy.py. Do not edit.",
  "import 'generated/app_localizations.dart';", '', 'class KoreanOnlyCopy {',
  '  KoreanOnlyCopy._();', '  static final _instance = KoreanOnlyCopy._();',
  '  static KoreanOnlyCopy forLocale(String language) {',
  "    if (language.split(RegExp('[-_]')).first != 'ko') {",
  "      throw StateError('Korean-only copy requested outside Korean feature scope');", '    }',
  '    return _instance;', '  }',
  '  static KoreanOnlyCopy fromLocalizations(AppLocalizations value) => forLocale(value.localeName);', '']
 for key,text in data.items():
  if key.startswith('@'): continue
  params=data.get('@'+key,{}).get('placeholders',{})
  assert set(re.findall(r'\{(\w+)\}',text)) == set(params),(key,params)
  assert not re.search(r'\{[^}]*,',text),'ICU requires an explicit generator extension'
  value=text.replace('\\','\\\\').replace("'","\\'").replace('$','\\$').replace('\r','\\r').replace('\n','\\n')
  for name in params: value=value.replace('{'+name+'}', '${'+name+'}')
  signature=(key+'('+', '.join(p.get('type','Object')+' '+name for name,p in params.items())+')') if params else 'get '+key
  lines.append(f"  String {signature} => '{value}';")
 lines.append('}')
 (ROOT/'lib/l10n/korean_only_copy.dart').write_text('\n'.join(lines)+'\n','utf-8')

if __name__=='__main__': generate()
