"""Generate offline Dart/native holiday data from the single reviewed JSON source.

Run --check in CI. Date/source changes must be reviewed in the JSON, not outputs.
"""
import argparse
import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'data/national_holidays_2026_2028.json'


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f'Duplicate JSON key: {key}')
        result[key] = value
    return result


def outputs():
    data = json.loads(SOURCE.read_text(encoding='utf-8'), object_pairs_hook=unique_object)
    assert data['years'] == [2026, 2027, 2028]
    assert set(data['countries']) == {'US','GB','ZA','IN','DE','BR','PH','AE'}
    dart = ['// Generated by tools/generate_national_holidays.py. Do not edit.',
            '// Source dates, scope, pending declarations and citations: data/national_holidays_2026_2028.json',
            'const nationalHolidayNames = <String, Map<String, Map<String, String>>>{']
    kotlin = ['// Generated by tools/generate_national_holidays.py. Do not edit.',
              'package com.hwani1103.shiftbell', '', 'object NationalHolidayDates {',
              '    val dates: Map<String, Set<String>> = mapOf(']
    for code, country in sorted(data['countries'].items()):
        assert country['sources'] and country['scope']
        dart.append(f'  "{code}": {{')
        kotlin.append(f'        "{code}" to setOf(')
        for date, names in sorted(country['days'].items()):
            parsed = dt.date.fromisoformat(date)
            assert parsed.isoformat() == date and parsed.year in data['years']
            assert names.get('en') and all(isinstance(n,str) and n.strip() for n in names.values())
            encoded = json.dumps(names, ensure_ascii=False).replace('$', '\\$')
            dart.append(f'    "{date}": {encoded},')
            kotlin.append(f'            "{date}",')
        expected = {str(y):sum(d.startswith(str(y)) for d in country['days']) for y in data['years']}
        assert country['counts'] == expected, f'{code}: update counts with reviewed data'
        dart.append('  },')
        kotlin.append('        ),')
    dart.append('};')
    kotlin += ['    )', '}']
    return {
        ROOT/'lib/generated/national_holidays.dart': '\n'.join(dart)+'\n',
        ROOT/'android/app/src/main/kotlin/com/hwani1103/shiftbell/NationalHolidayDates.kt': '\n'.join(kotlin)+'\n',
    }


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, expected in outputs().items():
        if args.check:
            assert path.read_text(encoding='utf-8') == expected, f'Stale generated holiday data: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding='utf-8', newline='\n')
    print('National holiday source and Dart/native parity: OK')
