"""Generate the native calendar widgets: a day/night garden with weekly cards."""
from pathlib import Path
R = Path(__file__).resolve().parents[1] / 'android/app/src/main/res/layout'

def cell(r,c,single):
    k=f'{r}_{c}'
    date_font = 12 if single else 14
    preview=('day','night','off')[c%3]
    color=('#4771D1','#6B6524','#EF5350')[c%3]
    notes=''.join(f'''<TextView android:id="@+id/memo{s}_{k}" android:layout_width="match_parent" android:layout_height="wrap_content"
      android:gravity="center" android:textSize="9.5dp" android:textColor="#465A59" android:includeFontPadding="false"
      android:maxLines="1" android:visibility="gone"/>''' for s in (1,2,3))
    return f'''<LinearLayout android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1"
      android:layout_marginLeft="1dp" android:layout_marginRight="1dp" android:orientation="vertical">
      <LinearLayout android:id="@+id/numwrap_{k}" android:layout_width="match_parent" android:layout_height="wrap_content" android:gravity="center" android:orientation="vertical">
        <TextView android:id="@+id/num_{k}" android:layout_width="wrap_content" android:layout_height="wrap_content" android:minWidth="23dp"
          android:gravity="center" android:paddingLeft="3dp" android:paddingRight="3dp" android:textSize="{date_font}dp" android:textStyle="bold"
          android:includeFontPadding="false" android:textColor="#263F3E" android:text="{r*7+c+1}"/>
      </LinearLayout>
      <FrameLayout android:layout_width="match_parent" android:layout_height="18dp">
        <ImageView android:id="@+id/pillbg_{k}" android:layout_width="match_parent" android:layout_height="match_parent" android:src="{color}" android:scaleType="fitXY" android:importantForAccessibility="no"/>
        <TextView android:id="@+id/pill_{k}" android:layout_width="match_parent" android:layout_height="match_parent" android:gravity="center"
          android:fontFamily="sans-serif" android:textSize="12dp" android:textStyle="bold" android:textColor="#FFFFFF"
          android:paddingLeft="1dp" android:paddingRight="1dp" android:includeFontPadding="false" android:maxLines="1" android:text="@string/widget_preview_{preview}"/>
      </FrameLayout>
      <LinearLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:gravity="top" android:orientation="vertical">{notes}</LinearLayout>
    </LinearLayout>'''

def layout(single):
    weekday_height = 16 if single else 23
    weekday_font = 12 if single else 13
    weekdays=f'<LinearLayout android:layout_width="match_parent" android:layout_height="{weekday_height}dp" android:orientation="horizontal">'+''.join(
          f'<TextView android:id="@+id/hdr_{c}" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1" android:gravity="center" android:textSize="{weekday_font}dp" android:textStyle="bold" android:textColor="#355B54" android:includeFontPadding="false" android:maxLines="1" android:text="@string/widget_weekday_{c}"/>' for c in range(7))+'</LinearLayout>'
    header=weekdays if single else '''<FrameLayout android:layout_width="match_parent" android:layout_height="30dp">
          <ImageView android:id="@+id/widget_day_period" android:layout_width="100dp" android:layout_height="30dp" android:layout_gravity="right" android:scaleType="fitXY" android:src="@drawable/widget_landscape_day" android:contentDescription="@string/widget_daytime"/>
          <TextView android:id="@+id/widget_date_header" android:layout_width="match_parent" android:layout_height="match_parent" android:layout_marginRight="100dp"
            android:paddingLeft="5dp" android:gravity="center_vertical" android:textSize="19dp" android:textStyle="bold" android:fontFamily="sans-serif-medium"
            android:textColor="#294E48" android:includeFontPadding="false" android:maxLines="1" android:autoSizeTextType="uniform"
            android:autoSizeMinTextSize="12dp" android:autoSizeMaxTextSize="19dp" android:text="@string/app_widget_calendar_label"/>
        </FrameLayout>''' + weekdays
    rows=''.join('<LinearLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:layout_marginTop="1dp" android:layout_marginBottom="1dp" android:background="@drawable/widget_week_surface" android:orientation="horizontal">'+''.join(cell(r,c,single) for c in range(7))+'</LinearLayout>' for r in range(1 if single else 3))
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/generate_calendar_widget_layouts.py. -->
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android" android:id="@+id/widget_panel" android:layout_width="match_parent" android:layout_height="match_parent" android:background="@drawable/calendar_widget_day" android:clipToOutline="true" android:layoutDirection="ltr">
  <ImageView android:id="@+id/widget_garden" android:layout_margin="8dp" android:layout_width="match_parent" android:layout_height="match_parent" android:src="@drawable/widget_garden_day" android:scaleType="fitXY" android:importantForAccessibility="no"/>
  <TextView android:id="@+id/empty_message" android:layout_width="match_parent" android:layout_height="match_parent" android:gravity="center" android:textSize="12sp" android:textColor="#294E48" android:visibility="gone" android:text="@string/widget_setup_schedule_first"/>
  <LinearLayout android:id="@+id/widget_content" android:layout_width="match_parent" android:layout_height="match_parent" android:paddingLeft="7dp" android:paddingRight="7dp" android:paddingTop="4dp" android:paddingBottom="4dp" android:orientation="vertical">{header}{rows}</LinearLayout>
</FrameLayout>
'''
for name,single in [('calendar_widget',False),('calendar_widget_week',True)]:
    (R/(name+'.xml')).write_text(layout(single),encoding='utf-8')
