// Generated by tools/generate_web_locale_assets.py. Do not edit.
(function () {
  'use strict';
  const copy = {
  "ko": {
    "name": "교대시계",
    "title": "교대시계 - 근무 스케줄 공유",
    "description": "친구가 공유한 근무 스케줄을 앱 설치 없이 바로 확인하세요.",
    "metaDescription": "교대시계로 공유된 친구의 근무 스케줄을 앱 설치 없이 바로 확인하세요.",
    "manifestName": "교대시계 - 일정 공유",
    "manifestDescription": "친구의 교대 근무 일정을 앱 없이 바로 확인하는 웹 뷰어"
  },
  "pt": {
    "name": "ShiftBell",
    "title": "ShiftBell - Compartilhar escala",
    "description": "Abra um link compartilhado para ver a escala atualizada."
  },
  "de": {
    "name": "ShiftBell",
    "title": "ShiftBell - Schichtplan teilen",
    "description": "Öffne einen geteilten Link, um den aktuellen Schichtplan anzusehen."
  },
  "en": {
    "name": "ShiftBell",
    "title": "ShiftBell - Schedule Sharing",
    "description": "Open a shared link to view the latest shift schedule."
  },
  "hi": {
    "name": "ShiftBell",
    "title": "ShiftBell - शेड्यूल शेयर करें",
    "description": "शेयर किया गया लिंक खोलकर नया शिफ्ट शेड्यूल देखें।"
  }
};
  function updateLocale() {
    const primary = (navigator.languages && navigator.languages[0]) || navigator.language || 'en';
    const requested = primary.toLowerCase().split(/[-_]/)[0];
    const lang = Object.prototype.hasOwnProperty.call(copy, requested) ? requested : 'en';
    const text = copy[lang];
    document.documentElement.lang = lang;
    document.title = text.title;
    for (const [selector, value] of [
      ['meta[name="description"]', text.metaDescription || text.description],
      ['meta[property="og:title"]', text.title],
      ['meta[property="og:description"]', text.description],
      ['meta[name="apple-mobile-web-app-title"]', text.name]
    ]) {
      const element = document.querySelector(selector);
      if (element) element.setAttribute('content', value);
    }
    const manifest = document.querySelector('link[rel="manifest"]');
    if (manifest) manifest.setAttribute('href', 'manifest_' + lang + '.json');
  }
  updateLocale();
  window.addEventListener('languagechange', updateLocale);
})();
